### ISSUE TITLE
Add GitHub Topic: gitlab-backup

### ISSUE THREAD

**Issue by katrinleinweber** [kreczko/gitlab-migrate#1]
Thanks for publishing this! In case you'd like to make [your repo more findable](https://github.com/topics/gitlab-backup), you could [add that topic](https://help.github.com/articles/about-topics/) ;-) Thank you!

**Comment by kreczko** [comment]
Thanks for the info! This is now done.

**Comment by katrinleinweber** [comment]
Cool, thank you :-)
